title: Stars & Signs
description: A tabletop role-playing game system about balancing life as a teenager with magical fights against cosmic horrors. 
markdown: kramdown
theme: slate
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme