title: Stars & Signs
description: A tabletop role-playing game about teenage life and cosmic horror
markdown: kramdown
theme: jekyll-theme-slate
baseurl: "/docs"
url: "https://stars-and-signs.github.io/stars-and-signs/"
plugins:
  - jekyll-remote-theme
