title: Stars & Signs
description: A tabletop role-playing game about teenage life and cosmic horror
markdown: kramdown
remote_theme: pages-themes/slate@v0.2.0
baseurl: "/docs"
url: "https://stars-and-signs.github.io/stars-and-signs/"
plugins:
  - jekyll-remote-theme
